### ISSUE TITLE
use gulp watch

### ISSUE THREAD

**Issue by jspaaks** [nlesc-sherlock/chicago#1]

**Comment by mkuzak** [comment]
Gulp should support following general tasks:
- [x] init
- [x] build
- [ ] dist
- [ ] clean
- [x] watch dev
- [ ] watch dist
- [x] help

and following subtasks:
- [x] eslint
- [x] tslint
- [x] beautify
- [x] compile ts
- [x] concat
- [x] make maps
- [ ] minify
- [ ] uglify
- [ ] change sources in html
- [x] run , restart server
- [x] refresh browsers
- [x] npm install
- [x] bower install
- [x] tsd install
- [ ] tasks
- [x] help message
