### ISSUE TITLE
migrate the TypeScript heatmap visualization from d3.js to dc.js

### ISSUE THREAD

**Issue by jspaaks** [nlesc-sherlock/chicago#11]

**Comment by mkuzak** [comment]
What is the rationale behind it?

**Comment by jspaaks** [comment]
Not sure what the rationale is/was. But it could be that you have one dc.js control that selects a range in time, and that a subsequent plot then shows the heatmap for that period. This would give the user a by-day overview first, and a within-day overview second.

**Comment by jspaaks** [comment]
So at this point we have TypeScript heatmap visualizations of date v time of day as well as day of week v time of day (quite similar to the original punchcard visualization but using colored SVG rect instead of SVG circles). Both visualizations use a crossfilter object, but without going through dc.js.

Closing this issue.
