### ISSUE TITLE
do we need heatmaps.js instead of d3 rects for increased performance?

### ISSUE THREAD

**Issue by jspaaks** [nlesc-sherlock/chicago#112]
[https://github.com/pa7/heatmap.js](https://github.com/pa7/heatmap.js)

**Comment by mkuzak** [comment]
It is possible that drawing the rectangles even for whole year does not have any considerable impact on performance. We need to first profile with big number of drawn elements.

**Comment by jspaaks** [comment]
Agree. See also issue #11.
