### ISSUE TITLE
styles are not updated on change

### ISSUE THREAD

**Issue by jspaaks** [nlesc-sherlock/chicago#73]
maybe something to do with the watch?

I fiddled with a css file, but the changes did not automatically make it to the browser. It did work when I stopped the gulp `dev-watch` task with Ctrl-C, then did a `gulp clean` (not sure that's necessary) then restarted `gulp dev-watch`

**Comment by mkuzak** [comment]
is this still the case, it does update for me

**Comment by jspaaks** [comment]
it works yay! Closing this issue.
